services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: swabscan_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: swabscan_app
    ports:
      - "8501:8501"
    environment:
      QDRANT_URL: "http://qdrant:6333"
    volumes:
      # mount your PDuddy download folder read-only
      - /mnt/ssd2/pduddy:/app/input:ro
    depends_on:
      - qdrant

volumes:
  qdrant_data:

