services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: swabscan_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: swabscan_app
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      QDRANT_URL: "http://qdrant:6333"
    volumes:
      - ./input:/app/input:ro
      - .:/app
    depends_on:
      - qdrant

volumes:
  qdrant_data:
